services:
  postgres:
    container_name: postgres-alpine
    image: postgres:17.5-alpine3.22
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pomostudy
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: